#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'openssh'
cookbook 'user'
cookbook 'runit'
cookbook 'nginx'
cookbook 'simple_iptables'
cookbook 'rvm', :git => "git://github.com/fnichol/chef-rvm.git"
cookbook 'homesick', :git => "git://github.com/cfitz/chef-homesick.git"
cookbook 'newrelic-sysmond'
cookbook 'jetty'
cookbook 'percona'
cookbook 'java', '=1.10.0'
cookbook 'hipsnip-jetty', :git => "https://github.com/hipsnip-cookbooks/jetty"
cookbook 'hipsnip-solr', :git => "https://github.com/hipsnip-cookbooks/solr"
cookbook 'fail2ban'
cookbook 'apt'

#
#site 'http://community.opscode.com/api/v1'
#
## cookbook 'chef-client'
#
## cookbook 'apache2', '>= 1.0.0'
#
## cookbook 'rvm',
##   :git => 'https://github.com/fnichol/chef-rvm'
#
## cookbook 'postgresql',
##   :git => 'https://github.com/findsyou/cookbooks',
##   :ref => 'postgresql-improvements'
