mlp:
  adapter: postgresql
  database: rails4bp_mlp
  username: rails4bp_mlp
  password: applejack
  host: dbhost
  pool: 5
  timeout: 5000
  db_id: 1	# ensure db_id is unique for each site
  ### If you change this setting you will need to
  ###   - restart sidekiq if you change this setting
  ###   - rebake all to posts using: `RAILS_ENV=production bundle exec rake posts:rebake`
  host_names:
    - rails4bp.equestria.com
    - rails4bp.equestria.internal

drwho:
  adapter: postgresql
  database: rails4bp_who
  username: rails4bp_who
  password: "Up the time stream without a TARDIS"
  host: dbhost
  pool: 5
  timeout: 5000
  db_id: 	# ensure db_id is unique for each site
  ### If you change this setting you will need to
  ###   - restart sidekiq if you change this setting
  ###   - rebake all to posts using: `RAILS_ENV=production bundle exec rake posts:rebake`
  host_names:
    - discuss.tardis.gallifrey
